### ISSUE TITLE
Support Cordova AAR installation

### ISSUE THREAD

**Issue by infil00p** [phonegap/phonegap-intellij-plugin#12]
@stevengill and I are currently working on cleaning up https://github.com/apache/cordova-android/pull/361 which would allow for automation of uploading to BinTray.  Assuming we can get that cleaned up, it'd be good to install the AAR instead of a JAR so that the code complete properly works.

**Comment by stevengill** [comment]
It is live on bintray https://bintray.com/cordova/maven/cordova-android

**Comment by imhotep** [comment]
Please try version 1.3
