### ISSUE TITLE
Must open Android Studio from command-line to install plugins

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-intellij-plugin#9]
_Original issue https://github.com/imhotep/PGDayEUWs2016/issues/4_

## Problem

I receive the following error when installing a plugin:

> **Error**
> You need to install NodeJS and plugman in order to be able to use plugins. If you are on Mac OS X make sure you run the following: `sudo launchctl config user path $PATH`

Updating my `PATH` and rebooting my Macbook does not solve the issue:

```bash
$ sudo launchctl config user path $PATH
Password:
Configuration applied. You must reboot for changes to take effect.
```

![image](https://cloud.githubusercontent.com/assets/21328/20731472/659755ac-b63f-11e6-9f57-e92bd2b3fa37.png)

## Workaround

The solution is to open Android Studio from the command-line, so that it inherits the environment:

```bash
$ open /Applications/Android\ Studio.app
```

## Solution

This issue is only happening on a few systems. We should find a way to solve it without requiring Android Studio to be launched from the command-line.

**Comment by imhotep** [comment]
Couldn't reproduce with latest version. I installed Android Studio on a brand new mac but it was also working on my previous mac. Going to close for now.
